export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';

export const AUTH_ERROR = 'AUTH ERROR';
export const USER_FETCHED = 'USER_FETCHED';

export const MISSION_SUCCESS = 'MISSION_SUCCESS';
export const MISSION_FETCH_REQUEST = 'MISSION_FETCH_REQUEST';
export const MISSION_FAIL = 'MISSION_FAIL';

export const EDIT_MISSION_SUCCESS = 'EDIT_MISSION_SUCCESS';
export const EDIT_MISSION_FETCH_REQUEST = 'EDIT_MISSION_FETCH_REQUEST';
export const EDIT_MISSION_FAIL = 'EDIT_MISSION_FAIL';

export const VISION_SUCCESS = 'VISION_SUCCESS';
export const VISION_FETCH_REQUEST = 'VISION_FETCH_REQUEST';
export const VISION_FAIL = 'VISION_FAIL';

export const EDIT_VISION_SUCCESS = 'EDIT_VISION_SUCCESS';
export const EDIT_VISION_FETCH_REQUEST = 'EDIT_VISION_FETCH_REQUEST';
export const EDIT_VISION_FAIL = 'EDIT_VISION_FAIL';

export const ALL_KPIS_SUCCESS = 'ALL_KPIS_SUCCESS';
export const ALL_KPIS_FAIL = 'ALL_KPIS_FAIL';
export const ALL_KPIS_FETCH_REQUEST = 'ALL_KPIS_FETCH_REQUEST';

export const KPI_SUCCESS = 'KPI_SUCCESS';
export const KPI_FAIL = 'KPI_FAIL';
export const KPI_FETCH_REQUEST = 'KPI_FETCH_REQUEST';

export const ADD_KPI_SUCCESS = 'ADD_KPI_SUCCESS';
export const ADD_KPI_FAIL = 'ADD_KPI_FAIL';
export const ADD_KPI_FETCH_REQUEST = 'ADD_KPI_FETCH_REQUEST';

export const EDIT_KPI_SUCCESS = 'EDIT_KPI_SUCCESS';
export const EDIT_KPI_FAIL = 'EDIT_KPI_FAIL';
export const EDIT_KPI_FETCH_REQUEST = 'EDIT_KPI_FETCH_REQUEST';

export const DELETE_KPI_SUCCESS = 'DELETE_KPI_SUCCESS';
export const DELETE_KPI_FAIL = 'DELETE_KPI_FAIL';
export const DELETE_KPI_FETCH_REQUEST = 'DELETE_KPI_FETCH_REQUEST';

export const ALL_OBJECTIVES_SUCCESS = 'ALL_OBJECTIVES_SUCCESS';
export const ALL_OBJECTIVES_FAIL = 'ALL_OBJECTIVES_FAIL';
export const ALL_OBJECTIVES_FETCH_REQUEST = 'ALL_OBJECTIVES_FETCH_REQUEST';

export const OBJECTIVE_SUCCESS = 'OBJECTIVE_SUCCESS';
export const OBJECTIVE_FAIL = 'OBJECTIVE_FAIL';
export const OBJECTIVE_FETCH_REQUEST = 'OBJECTIVE_FETCH_REQUEST';

export const ADD_OBJECTIVE_SUCCESS = 'ADD_OBJECTIVE_SUCCESS';
export const ADD_OBJECTIVE_FAIL = 'ADD_OBJECTIVE_FAIL';
export const ADD_OBJECTIVE_FETCH_REQUEST = 'ADD_OBJECTIVE_FETCH_REQUEST';

export const EDIT_OBJECTIVE_SUCCESS = 'EDIT_OBJECTIVE_SUCCESS';
export const EDIT_OBJECTIVE_FAIL = 'EDIT_OBJECTIVE_FAIL';
export const EDIT_OBJECTIVE_FETCH_REQUEST = 'EDIT_OBJECTIVE_FETCH_REQUEST';

export const DELETE_OBJECTIVE_SUCCESS = 'DELETE_OBJECTIVE_SUCCESS';
export const DELETE_OBJECTIVE_FAIL = 'DELETE_OBJECTIVE_FAIL';
export const DELETE_OBJECTIVE_FETCH_REQUEST = 'DELETE_OBJECTIVE_FETCH_REQUEST';

export const OBJECTIVE_TASKS_SUCCESS = 'OBJECTIVE_TASKS_SUCCESS';
export const OBJECTIVE_TASKS_FETCH_REQUEST = 'OBJECTIVE_TASKS_FETCH_REQUEST';
export const OBJECTIVE_TASKS_FAIL = 'OBJECTIVE_TASKS_FAIL';

export const ALL_TASKS_SUCCESS = 'ALL_TASKS_SUCCESS';
export const ALL_TASKS_FAIL = 'ALL_TASKS_FAIL';
export const ALL_TASKS_FETCH_REQUEST = 'ALL_TASKS_FETCH_REQUEST';

export const TASK_SUCCESS = 'TASK_SUCCESS';
export const TASK_FAIL = 'TASK_FAIL';
export const TASK_FETCH_REQUEST = 'TASK_FETCH_REQUEST';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';
export const ADD_TASK_FETCH_REQUEST = 'ADD_TASK_FETCH_REQUEST';

export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAIL = 'EDIT_TASK_FAIL';
export const EDIT_TASK_FETCH_REQUEST = 'EDIT_TASK_FETCH_REQUEST';

export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';
export const DELETE_TASK_FETCH_REQUEST = 'DELETE_TASK_FETCH_REQUEST';

export const ALL_ASSIGNED_TASKS_SUCCESS = 'ALL_ASSIGNED_TASKS_SUCCESS';
export const ALL_ASSIGNED_TASKS_FAIL = 'ALL_ASSIGNED_TASKS_FAIL';
export const ALL_ASSIGNED_TASKS_FETCH_REQUEST = 'ALL_ASSIGNED_TASKS_FETCH_REQUEST';

export const ASSIGNED_TASK_SUCCESS = 'ASSIGNED_TASK_SUCCESS';
export const ASSIGNED_TASK_FAIL = 'ASSIGNED_TASK_FAIL';
export const ASSIGNED_TASK_FETCH_REQUEST = 'ASSIGNED_TASK_FETCH_REQUEST';

export const ADD_ASSIGNED_TASK_SUCCESS = 'ADD_ASSIGNED_TASK_SUCCESS';
export const ADD_ASSIGNED_TASK_FAIL = 'ADD_ASSIGNED_TASK_FAIL';
export const ADD_ASSIGNED_TASK_FETCH_REQUEST = 'ADD_ASSIGNED_TASK_FETCH_REQUEST';

export const EDIT_ASSIGNED_TASK_SUCCESS = 'EDIT_ASSIGNED_TASK_SUCCESS';
export const EDIT_ASSIGNED_TASK_FAIL = 'EDIT_ASSIGNED_TASK_FAIL';
export const EDIT_ASSIGNED_TASK_FETCH_REQUEST = 'EDIT_ASSIGNED_TASK_FETCH_REQUEST';

export const DELETE_ASSIGNED_TASK_SUCCESS = 'DELETE_ASSIGNED_TASK_SUCCESS';
export const DELETE_ASSIGNED_TASK_FAIL = 'DELETE_ASSIGNED_TASK_FAIL';
export const DELETE_ASSIGNED_TASK_FETCH_REQUEST = 'DELETE_ASSIGNED_TASK_FETCH_REQUEST';

export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_FETCH_REQUEST = 'ALL_USERS_FETCH_REQUEST';
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL';

export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FAIL = 'USER_FAIL';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FETCH_REQUEST = 'ADD_USER_FETCH_REQUEST';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FETCH_REQUEST = 'EDIT_USER_FETCH_REQUEST';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FETCH_REQUEST = 'DELETE_USER_FETCH_REQUEST';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const ALL_TEAMS_SUCCESS = 'ALL_TEAMS_SUCCESS';
export const ALL_TEAMS_FETCH_REQUEST = 'ALL_TEAMS_FETCH_REQUEST';
export const ALL_TEAMS_FAIL = 'ALL_TEAMS_FAIL';

export const TEAM_SUCCESS = 'TEAM_SUCCESS';
export const TEAM_FETCH_REQUEST = 'TEAM_FETCH_REQUEST';
export const TEAM_FAIL = 'TEAM_FAIL';

export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FETCH_REQUEST = 'ADD_TEAM_FETCH_REQUEST';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';

export const EDIT_TEAM_SUCCESS = 'EDIT_TEAM_SUCCESS';
export const EDIT_TEAM_FETCH_REQUEST = 'EDIT_TEAM_FETCH_REQUEST';
export const EDIT_TEAM_FAIL = 'EDIT_TEAM_FAIL';

export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FETCH_REQUEST = 'DELETE_TEAM_FETCH_REQUEST';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';

export const ALL_ROLES_SUCCESS = 'ALL_ROLES_SUCCESS';
export const ALL_ROLES_FETCH_REQUEST = 'ALL_ROLES_FETCH_REQUEST';
export const ALL_ROLES_FAIL = 'ALL_ROLES_FAIL';

export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS';
export const ALL_CATEGORIES_FETCH_REQUEST = 'ALL_CATEGORIES_FETCH_REQUEST';
export const ALL_CATEGORIES_FAIL = 'ALL_CATEGORIES_FAIL';

export const ALL_STATUS_SUCCESS = 'ALL_STATUS_SUCCESS';
export const ALL_STATUS_FETCH_REQUEST = 'ALL_STATUS_FETCH_REQUEST';
export const ALL_STATUS_FAIL = 'ALL_STATUS_FAIL';

export const ALL_PILLARS_SUCCESS = 'ALL_PILLARS_SUCCESS';
export const ALL_PILLARS_FETCH_REQUEST = 'ALL_PILLARS_FETCH_REQUEST';
export const ALL_PILLARS_FAIL = 'ALL_PILLARS_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';