export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const AUTH_ERROR = 'AUTH ERROR';
export const USER_FETCHED = 'USER_FETCHED';

export const ALL_KPIS_SUCCESS = 'ALL_KPIS_SUCCESS';
export const ALL_KPIS_FAIL = 'ALL_KPIS_FAIL';
export const ALL_KPIS_FETCH_REQUEST = 'ALL_KPIS_FETCH_REQUEST';

export const KPI_SUCCESS = 'KPI_SUCCESS';
export const KPI_FAIL = 'KPI_FAIL';
export const KPI_FETCH_REQUEST = 'KPI_FETCH_REQUEST';

export const ADD_KPI_SUCCESS = 'ADD_KPI_SUCCESS';
export const ADD_KPI_FAIL = 'ADD_KPI_FAIL';
export const ADD_KPI_FETCH_REQUEST = 'ADD_KPI_FETCH_REQUEST';

export const EDIT_KPI_SUCCESS = 'EDIT_KPI_SUCCESS';
export const EDIT_KPI_FAIL = 'EDIT_KPI_FAIL';
export const EDIT_KPI_FETCH_REQUEST = 'EDIT_KPI_FETCH_REQUEST';

export const DELETE_KPI_SUCCESS = 'DELETE_KPI_SUCCESS';
export const DELETE_KPI_FAIL = 'DELETE_KPI_FAIL';
export const DELETE_KPI_FETCH_REQUEST = 'DELETE_KPI_FETCH_REQUEST';

export const ALL_OBJECTIVES_SUCCESS = 'ALL_OBJECTIVES_SUCCESS';
export const ALL_OBJECTIVES_FAIL = 'ALL_OBJECTIVES_FAIL';
export const ALL_OBJECTIVES_FETCH_REQUEST = 'ALL_OBJECTIVES_FETCH_REQUEST';

export const OBJECTIVE_SUCCESS = 'OBJECTIVE_SUCCESS';
export const OBJECTIVE_FAIL = 'OBJECTIVE_FAIL';
export const OBJECTIVE_FETCH_REQUEST = 'OBJECTIVE_FETCH_REQUEST';

export const ADD_OBJECTIVE_SUCCESS = 'ADD_OBJECTIVE_SUCCESS';
export const ADD_OBJECTIVE_FAIL = 'ADD_OBJECTIVE_FAIL';
export const ADD_OBJECTIVE_FETCH_REQUEST = 'ADD_OBJECTIVE_FETCH_REQUEST';

export const EDIT_OBJECTIVE_SUCCESS = 'EDIT_OBJECTIVE_SUCCESS';
export const EDIT_OBJECTIVE_FAIL = 'EDIT_OBJECTIVE_FAIL';
export const EDIT_OBJECTIVE_FETCH_REQUEST = 'EDIT_OBJECTIVE_FETCH_REQUEST';

export const DELETE_OBJECTIVE_SUCCESS = 'DELETE_OBJECTIVE_SUCCESS';
export const DELETE_OBJECTIVE_FAIL = 'DELETE_OBJECTIVE_FAIL';
export const DELETE_OBJECTIVE_FETCH_REQUEST = 'DELETE_OBJECTIVE_FETCH_REQUEST';

export const ALL_TASKS_SUCCESS = 'ALL_TASKS_SUCCESS';
export const ALL_TASKS_FAIL = 'ALL_TASKS_FAIL';
export const ALL_TASKS_FETCH_REQUEST = 'ALL_TASKS_FETCH_REQUEST';

export const TASK_SUCCESS = 'TASK_SUCCESS';
export const TASK_FAIL = 'TASK_FAIL';
export const TASK_FETCH_REQUEST = 'TASK_FETCH_REQUEST';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';
export const ADD_TASK_FETCH_REQUEST = 'ADD_TASK_FETCH_REQUEST';

export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAIL = 'EDIT_TASK_FAIL';
export const EDIT_TASK_FETCH_REQUEST = 'EDIT_TASK_FETCH_REQUEST';

export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';
export const DELETE_TASK_FETCH_REQUEST = 'DELETE_TASK_FETCH_REQUEST';

export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_FETCH_REQUEST = 'ALL_USERS_FETCH_REQUEST';
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FETCH_REQUEST = 'ADD_USER_FETCH_REQUEST';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FETCH_REQUEST = 'EDIT_USER_FETCH_REQUEST';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FETCH_REQUEST = 'DELETE_USER_FETCH_REQUEST';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';